/** Shared category list used across the site (partner portal, sliders, etc.) */
export const PARTNER_CATEGORIES = [
  {
    id: 'Attendant',
    name: 'Elder Care Companion',
    image: '/image/categoryimg/gaurdiankids.png',
    screen: '/pages/Attendant',
    iconBg: '#E8F0FE',
    description: 'Provide compassionate care and companionship for senior citizens and elderly parents.',
  },
  {
    id: 'GaurdianKids',
    name: 'Guardian For Kids',
    image: '/image/categoryimg/gaurdiankids.png',
    screen: '/pages/GuardianKids',
    iconBg: '#FFF4E5',
    description: 'Trusted childcare and guardian services for families who need reliable support.',
  },
  {
    id: 'copessenger',
    name: 'Co-Pessenger For Travel',
    image: '/image/categoryimg/copessanger.png',
    screen: '/pages/Attendant',
    iconBg: '#E8F0FE',
    description: 'Accompany travellers who need assistance during journeys and hospital visits.',
  },
  {
    id: 'mehndi',
    name: 'Mehndi Artist',
    image: '/image/categoryimg/mehndi.png',
    screen: '/pages/Mehndi',
    iconBg: '#FFF8E1',
    description: 'Offer professional mehndi artistry for weddings, festivals, and special occasions.',
  },
  {
    id: 'Tiffin Service',
    name: 'Food For Patient & Tiffin Service',
    image: '/image/categoryimg/foodpatients.png',
    screen: '/pages/tiffinservice',
    iconBg: '#F1F8E9',
    description: 'Deliver nutritious meals and tiffin services for patients and health-conscious customers.',
  },
  {
    id: 'salonMakeup',
    name: 'Salon and Makeup',
    image: '/image/categoryimg/salon.png',
    screen: '/pages/Salon',
    iconBg: '#FCE4EC',
    description: 'Beauty, salon, and makeup services delivered at home or at your studio.',
  },
  {
    id: 'petWalker',
    name: 'Pet Walker',
    image: '/image/categoryimg/petwalker-removebg-preview.png',
    screen: '/pages/petwalker',
    iconBg: '#F0FDF4',
    description: 'Pet walking, grooming, and care services for pet owners in your locality.',
  },
  {
    id: 'pandit',
    name: 'Booking for Pandit Ji',
    image: '/image/categoryimg/pandit.png',
    screen: '/pages/Pandit',
    iconBg: '#FFF1F1',
    description: 'Religious ceremonies, pooja, and spiritual services for households and events.',
  },
  {
    id: 'school',
    name: 'School Uniform & Accessories',
    image: '/image/categoryimg/schooluniform.png',
    screen: '/pages/School',
    iconBg: '#F3E5F5',
    description: 'Supply school uniforms, bags, and educational accessories to parents and schools.',
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce',
    image: '/image/categoryimg/school.png',
    screen: '/pages/ecommerce',
    iconBg: '#E8F5E9',
    description: 'Sell products online through the Sevadoot marketplace to a wide customer base.',
  },
  {
    id: 'groceries',
    name: 'Healthy Food & Groceries',
    image: '/image/categoryimg/healthyfood.png',
    screen: '/pages/Groceries',
    iconBg: '#E8F5E9',
    description: 'Healthy food items, organic groceries, and daily essentials for local delivery.',
  },
  {
    id: 'hotel',
    name: 'Resort & Farmhouse Booking',
    image: '/image/categoryimg/resort.png',
    screen: '/pages/Hotel',
    iconBg: '#E0F2F1',
    description: 'List resorts, farmhouses, and holiday stays for travellers on Sevadoot.',
  },
  {
    id: 'cosmetic',
    name: 'Cosmetic',
    image: '/image/categoryimg/makeup.png',
    screen: '/pages/Cosmetic',
    iconBg: '#FCE4EC',
    description: 'Cosmetics, skincare, and beauty products for retail and home delivery.',
  },
  {
    id: 'Nurse',
    name: 'Nurse For First Aid',
    image: '/image/categoryimg/nurse.png',
    screen: '/pages/nurse',
    iconBg: '#FFF3E0',
    description: 'First-aid nursing, home nursing, and basic medical assistance services.',
  },
  {
    id: 'Nursed',
    name: 'Pregnancy & Ladies Health Issues',
    image: '/image/categoryimg/womenpr.png',
    screen: '/pages/ladies',
    iconBg: '#FFF3E0',
    description: 'Specialized care for pregnancy, postnatal support, and women\'s health needs.',
  },
  {
    id: 'Gym',
    name: 'Premium Gym Membership',
    image: '/image/categoryimg/gym.png',
    screen: '/pages/Gym',
    iconBg: '#EFEBE9',
    description: 'Gym memberships, fitness training, and wellness programs for health enthusiasts.',
  },
  {
    id: 'physiotherapist',
    name: 'Physiotherapist',
    image: '/image/categoryimg/physo.png',
    screen: '/pages/physiotherapist',
    iconBg: '#E0F7FA',
    description: 'Physiotherapy and rehabilitation services at home or at your clinic.',
  },
  {
    id: 'luxuryProduct',
    name: 'Luxury Product',
    image: '/image/categoryimg/luxuryitems.png',
    screen: '/pages/Luxury',
    iconBg: '#EDE7F6',
    description: 'Premium and luxury products for discerning customers on Sevadoot.',
  },
  {
    id: 'Fashion',
    name: 'Fashion & Lifestyle',
    image: '/image/categoryimg/fashionlifestyle.png',
    screen: '/pages/fashion',
    iconBg: '#EDE7F6',
    description: 'Fashion apparel, lifestyle products, and trend-driven retail offerings.',
  },
];

export const PARTNER_BENEFITS = [
  {
    title: 'Reach More Customers',
    description: 'Get discovered by thousands of users searching for services on Sevadoot every day.',
  },
  {
    title: 'Easy Booking Management',
    description: 'Manage appointments, schedules, and customer requests from one simple dashboard.',
  },
  {
    title: 'Timely Payments',
    description: 'Receive secure and transparent payments directly to your registered bank account.',
  },
  {
    title: 'Brand Visibility',
    description: 'Your profile and services appear under your chosen category with your brand identity.',
  },
  {
    title: 'Training & Support',
    description: 'Our partner support team helps you onboard, verify KYC, and grow your business.',
  },
  {
    title: 'Flexible Work',
    description: 'Set your availability, service areas, and pricing — work on your own terms.',
  },
];

export const PARTNER_STEPS = [
  {
    step: 1,
    title: 'Explore Categories',
    description: 'Browse all Sevadoot service categories in the Know More tab and choose the one that matches your expertise.',
  },
  {
    step: 2,
    title: 'Complete Registration',
    description: 'Fill the Register Now form with personal details, address, category, KYC documents, and references.',
  },
  {
    step: 3,
    title: 'Document Verification',
    description: 'Our team verifies your Aadhar, PAN, bank details, and references within 24–48 business hours.',
  },
  {
    step: 4,
    title: 'Profile Activation',
    description: 'Once approved, your partner profile goes live under your selected category on Sevadoot.',
  },
  {
    step: 5,
    title: 'Start Earning',
    description: 'Receive booking requests, serve customers, and grow your business with Sevadoot.',
  },
];
